### ISSUE TITLE
Automatically add files from Core into the XCode Project when added

### ISSUE THREAD

**Issue by Bathlamos** [Bathlamos/RTDC#16]

**Comment by Nicolas-M** [comment]
Can we / should we solve this during our validation Sprint?

**Comment by Nicolas-M** [comment]
After a long search, I'm not sure this is possible with Xcode. Most people suggest using folder references when adding files, so that they are kept up to date. However, for j2ObjC to work, the source files need to be added as groups. 

Another solution was to write a script to copy the files when building the project. However, none of my attempts proved fruitful.

So, I don't think it's possible. Since the core should be complete by the time we tackle the entire iOS client, I think we can close this issue. Adding the files manually every time the core changes should be good enough in my opinion.

@Bathlamos, do you confirm / agree with the above?

**Comment by Nicolas-M** [comment]
Having moved the j2ObjC command to gradle, we now have easier access to the Objective C files. Although new files cannot be added automatically, edited, translated files will be refreshed automatically. This works because the files themselves are added as "Folder References" in XCode.

Since a solution has been found, I'm closing this issue.
