### ISSUE TITLE
Develop iOS app which implements the LoginView interface

### ISSUE THREAD

**Issue by Bathlamos** [Bathlamos/RTDC#30]
One can login on the app. To do that, HTTPRequest, Factory and a few other platform-dependent classes will have to be implemented first.

**Comment by Nicolas-M** [comment]
A test app using the transpiled objective-c files has been started. All interfaces from the core have been implemented, with the exception of the dispatcher. The swift code and transpiling solution are working well. 

In the current implementation, we make async calls using a shared NSURLSession. 

Since the core is going through major changes, I'm stopping the iOS development until these changes are pushed to the master.

**Comment by Nicolas-M** [comment]
This test demonstrated our ability to transpile our core and use it in iOS. I think Apple made a lot of changes in the Swift programming language since then, so the code used here will have to be updated.

We'll have to look into it once we start the iOS application.
