### ISSUE TITLE
Créer un diagramme pour la base de données

### ISSUE THREAD

**Issue by Shern** [Bathlamos/RTDC#41]
Diagramme le plus complet possible d'entitiés/relations de la base de données pour le document Analysys Report.

**Comment by Nicolas-M** [comment]
The diagram included in the current report will need to be reviewed as to reflect the changes in how the Action Plan component works, and to include the necessary tables for the communication hub and notifications.

However, for the time being, the current diagram illustrates the core functionality, enough for the report. Since the Analysis Report has been submitted, I am closing this issue.
