### ISSUE TITLE
Add cards to Action Plan

### ISSUE THREAD

**Issue by Bathlamos** [Bathlamos/RTDC#56]

**Comment by Nicolas-M** [comment]
I created a custom dialog for when we click on a card in the action plan. I still need to plug it to the back end, but users will (eventually) be able to quickly change the status of an action, edit it and even delete it.

Known issues:
* Leaving the action plan and returning to the action plan fragment (via the drawer menu) makes all the cards disappear. (Probably due to my addition of a dialog)
* I had to make a few things final, and some other things static. We'll have to check if it affects anything. If it does, we'll have to review the code.
* I'm not too fond of the fact that we have to scroll in the dialog. Let's discuss this in a few hours.

**Comment by Nicolas-M** [comment]
Dialog now works as expected. There's no longer a scroll, and all the other mentioned above have been resolved. All there's left to do (in my opinion) is:
* Review the colors (especially the various greys being used)
* Style the Edit, Delete & Done button so that the colors change on click.
* Dialog disappears on the rotation of the device, which might not be too big of a deal.

**Comment by Nicolas-M** [comment]
The cards look fantastic! The client seemed to like the UI, so I'll be closing this issue.
